CREATE TABLE IF NOT EXISTS pharmacy_settings (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  pharmacy_name VARCHAR(200) NOT NULL,
  gstin VARCHAR(15) NULL,
  drug_license_numbers TEXT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
